title : ULRICH WHITMAN DJEUTSA NODEM 
logo: 
description: portfolio qui met en évidence le l'exploitation, le traitement, l'analyse et la valorisation des données
projet1: création d'un modele d'apprentissage automatique qui permet de prédir un défaut de crédit 
theme: regression logistique
